CREATE DATABASE IF NOT EXISTS dzvisual_nakburger
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dzvisual_nakburger;

CREATE TABLE IF NOT EXISTS stalls (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  type VARCHAR(100) NOT NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 4.5,
  reviews INT UNSIGNED NOT NULL DEFAULT 0,
  specialty VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL,
  offset_lat DECIMAL(10,7) NOT NULL DEFAULT 0,
  offset_lng DECIMAL(10,7) NOT NULL DEFAULT 0,
  menu_signature JSON NOT NULL,
  menu_sides JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
