CREATE DATABASE IF NOT EXISTS dzvisual_nakburger
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dzvisual_nakburger;

CREATE TABLE IF NOT EXISTS stalls (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  type VARCHAR(100) NOT NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 4.5,
  reviews INT UNSIGNED NOT NULL DEFAULT 0,
  specialty VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL,
  offset_lat DECIMAL(10,7) NOT NULL DEFAULT 0,
  offset_lng DECIMAL(10,7) NOT NULL DEFAULT 0,
  menu_signature JSON NOT NULL,
  menu_sides JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stall_owners (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  stall_id INT UNSIGNED NOT NULL,
  owner_name VARCHAR(191) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_stall_owner_stall (stall_id),
  UNIQUE KEY uniq_stall_owner_username (username),
  CONSTRAINT fk_stall_owners_stall FOREIGN KEY (stall_id) REFERENCES stalls (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stall_staff (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  stall_id INT UNSIGNED NOT NULL,
  staff_name VARCHAR(191) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_suspended TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_stall_staff_username (stall_id, username),
  CONSTRAINT fk_stall_staff_stall FOREIGN KEY (stall_id) REFERENCES stalls (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_code VARCHAR(40) NOT NULL,
  stall_id INT UNSIGNED NOT NULL,
  stall_name VARCHAR(191) NOT NULL,
  customer_name VARCHAR(191) NOT NULL DEFAULT 'Guest',
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'received',
  order_items JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_orders_order_code (order_code),
  KEY idx_orders_stall_created (stall_id, created_at),
  CONSTRAINT fk_orders_stall FOREIGN KEY (stall_id) REFERENCES stalls (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
